[package]
name = "mas-policy"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.66"
opa-wasm = { git = "https://github.com/matrix-org/rust-opa-wasm.git" }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["io-util", "rt"] }
tracing = "0.1.37"
wasmtime = { version = "1.0.1", default-features = false, features = ["async", "cranelift"] }

mas-data-model = { path = "../data-model" }
oauth2-types = { path = "../oauth2-types" }

[features]
cache = ["wasmtime/cache"]
