[package]
name = "mas-policy"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
opa-wasm = { git = "https://github.com/matrix-org/rust-opa-wasm.git" }
serde.workspace = true
serde_json.workspace = true
schemars = {version = "0.8.13", optional = true }
thiserror.workspace = true
tokio = { version = "1.32.0", features = ["io-util", "rt"] }
tracing.workspace = true
wasmtime = { version = "12.0.1", default-features = false, features = ["async", "cranelift"] }

mas-data-model = { path = "../data-model" }
oauth2-types = { path = "../oauth2-types" }

[dev-dependencies]
tokio = { version = "1.32.0", features = ["fs", "rt", "macros"] }

[features]
cache = ["wasmtime/cache"]
jsonschema = ["dep:schemars"]

[[bin]]
name = "schema"
required-features = ["jsonschema"]
