[package]
name = "mas-policy"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.72"
opa-wasm = { git = "https://github.com/matrix-org/rust-opa-wasm.git" }
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1.0.104"
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["io-util"] }
tracing = "0.1.37"
wasmtime = { version = "11.0.1", default-features = false, features = ["async", "cranelift"] }

mas-data-model = { path = "../data-model" }
oauth2-types = { path = "../oauth2-types" }

[dev-dependencies]
tokio = { version = "1.29.1", features = ["fs", "rt", "macros"] }

[features]
cache = ["wasmtime/cache"]
