[package]
name = "mas-policy"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.62"
opa-wasm = { git = "https://github.com/matrix-org/rust-opa-wasm.git" }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["io-util", "rt"] }
tracing = "0.1.36"
wasmtime = "0.39.1"

mas-data-model = { path = "../data-model" }
oauth2-types = { path = "../oauth2-types" }
