[package]
name = "mas-policy"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow.workspace = true
opa-wasm = { git = "https://github.com/matrix-org/rust-opa-wasm.git" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { version = "1.31.0", features = ["io-util"] }
tracing.workspace = true
wasmtime = { version = "11.0.1", default-features = false, features = ["async", "cranelift"] }

mas-data-model = { path = "../data-model" }
oauth2-types = { path = "../oauth2-types" }

[dev-dependencies]
tokio = { version = "1.31.0", features = ["fs", "rt", "macros"] }

[features]
cache = ["wasmtime/cache"]
