[package]
name = "mas-router"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
axum = { version = "0.5.13", default-features = false }
serde = { version = "1.0.142", features = ["derive"] }
serde_urlencoded = "0.7.1"
serde_with = "2.0.0"
url = "2.2.2"
