[package]
name = "mas-router"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
axum = { version = "0.6.20", default-features = false }
serde.workspace = true
serde_urlencoded = "0.7.1"
url.workspace = true
ulid = "1.0.0"
