doc-valid-idents = ["OpenID", "OAuth", ".."]

disallowed-methods = [
    { path = "rand::thread_rng", reason = "do not create rngs on the fly, pass them as parameters" },
    { path = "chrono::Utc::now", reason = "source the current time from the clock instead" },
    { path = "ulid::Ulid::from_datetime", reason = "use Ulid::from_datetime_with_source instead" },
    { path = "ulid::Ulid::new", reason = "use Ulid::from_datetime_with_source instead" },
]

disallowed-types = [
    "rand::OsRng",
    { path = "std::path::PathBuf", reason = "use camino::Utf8PathBuf instead" },
    { path = "std::path::Path", reason = "use camino::Utf8Path instead" },
]
