apiVersion: apps/v1
kind: Deployment
metadata:
  name: well-known-{{ include "mas.fullname" . }}
  labels:
{{ include "mas.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
			{{- include "well-known.selectorLabels" . | nindent 6 }}
  template:
    metadata:
			{{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "well-known.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    	{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    	{{- end }}
      serviceAccountName: {{ template "mas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "caddy:2.7.6"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          ports:
            - name: well-known
              containerPort: 8448
              protocol: TCP
          env:
          volumeMounts:
            - name: well-known
              mountPath: /etc/caddy/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: well-known
          configMap:
            name: well-known