/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SessionsIndexImport } from './routes/sessions.index'
import { Route as SessionsBrowsersImport } from './routes/sessions.browsers'
import { Route as SessionsIdImport } from './routes/sessions.$id'
import { Route as DevicesIdImport } from './routes/devices.$id'
import { Route as ClientsIdImport } from './routes/clients.$id'
import { Route as EmailsIdVerifyImport } from './routes/emails.$id.verify'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SessionsIndexRoute = SessionsIndexImport.update({
  path: '/sessions/',
  getParentRoute: () => rootRoute,
} as any)

const SessionsBrowsersRoute = SessionsBrowsersImport.update({
  path: '/sessions/browsers',
  getParentRoute: () => rootRoute,
} as any)

const SessionsIdRoute = SessionsIdImport.update({
  path: '/sessions/$id',
  getParentRoute: () => rootRoute,
} as any)

const DevicesIdRoute = DevicesIdImport.update({
  path: '/devices/$id',
  getParentRoute: () => rootRoute,
} as any)

const ClientsIdRoute = ClientsIdImport.update({
  path: '/clients/$id',
  getParentRoute: () => rootRoute,
} as any)

const EmailsIdVerifyRoute = EmailsIdVerifyImport.update({
  path: '/emails/$id/verify',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/clients/$id': {
      preLoaderRoute: typeof ClientsIdImport
      parentRoute: typeof rootRoute
    }
    '/devices/$id': {
      preLoaderRoute: typeof DevicesIdImport
      parentRoute: typeof rootRoute
    }
    '/sessions/$id': {
      preLoaderRoute: typeof SessionsIdImport
      parentRoute: typeof rootRoute
    }
    '/sessions/browsers': {
      preLoaderRoute: typeof SessionsBrowsersImport
      parentRoute: typeof rootRoute
    }
    '/sessions/': {
      preLoaderRoute: typeof SessionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/emails/$id/verify': {
      preLoaderRoute: typeof EmailsIdVerifyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ClientsIdRoute,
  DevicesIdRoute,
  SessionsIdRoute,
  SessionsBrowsersRoute,
  SessionsIndexRoute,
  EmailsIdVerifyRoute,
])

/* prettier-ignore-end */
