name: Build and publish docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/matrix-org/matrix-authentication-service:sha-${{ github.sha }}
