name: CI for tools

on:
  push:
    paths: 
      - 'tools/**'
  pull_request:
    paths:
      - 'tools/**'

concurrency:
  group: tools-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  syn2mas-lint:
    name: Check syn2mas style
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.5.3

      - name: Install Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version-file: ./tools/syn2mas/.nvmrc

      - name: Install Node dependencies
        working-directory: ./tools/syn2mas
        run: npm ci

      - name: Lint
        working-directory: ./tools/syn2mas
        run: npm run lint

  tests-done:
    name: Tests done
    if: ${{ always() }}
    needs:
      - syn2mas-lint
    runs-on: ubuntu-latest

    steps:
      - uses: matrix-org/done-action@v2
        with:
          needs: ${{ toJSON(needs) }}
